export const SET_LOADING = "SET_LOADING";
export const GET_BREEDS_REQUEST = "GET_BREEDS_REQUEST";
export const INIT_ALL_BREEDS = "INIT_ALL_BREEDS";
export const ADD_DOG_IMG_REQUEST = "ADD_DOG_IMG_REQUEST";
export const ADD_DOG_IMG = "ADD_DOG_IMG";
export const INCREMENT_IMAGE_LIKE = "INCREMENT_IMAGE_LIKE";
